declare module '@jlongster/sql.js'
declare module 'absurd-sql'
declare module 'absurd-sql/dist/indexeddb-backend'
declare module 'absurd-sql/dist/indexeddb-main-thread'
declare module 'sqlite-parser'
